DROP TABLE IF EXISTS `shout`;
CREATE TABLE `shout` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `body` VARCHAR(45) NOT NULL COMMENT '',
  `user_id` VARCHAR(45) NOT NULL COMMENT '',
  `vote` INT NULL DEFAULT 0 COMMENT '',
  `shouted_on` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '');
